- name: Install catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: setup NPM source ## NPM node package manager ##
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
      disable_gpg_check: true

  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: out ## register is variable, id roboshop output stores in register output ##
    ignore_errors: true

  - when: out.rc != 0
    name: create user roboshop ## creating roboshop user ##
    become: yes
    ansible.builtin.user:
      name: roboshop

  - name: check /app directory exist or not
    ansible.builtin.stat: ## checks /app directory exist or not using ## stat ##
      path: /app
    register: directory

  - name: print the directory stats ## printing output of directory ##
    ansible.builtin.debug:
     msg: "output: {{directory}}"

  - when: directory.stat.exists ==false ## In ansible server catalogue configar output is stat:exists: == false then creats directory ## 
    name: create /app directory
    ansible.builtin.file: ## directory creating module is [ file ] ##
      path: /app
      state: directory

  - name: download catalogue application ## application code downloading in tmp directory ##
    ansible:builtin.get_url: ## get_url a module in Ansible used to download files from the internet like http or https or ftp many more ##
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: exact catalogue application
    ansible.builtin.unarchive: ## unarchive is used for unzip application ## 
      src: /tmp/catalogue.zip ## which file is to exact that file give in src ##
      dest: /app ## exact in /app directory##
      remote_src: yes            