- name: Install web component ## installing web component ##
  hosts: web
  become: yes
  tasks:
  - name: install nginx ## installing nginx ##
    ansible.builtin.yum:
      name: nginx
      state: installed

  - name: start and enable nginx 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
 
  - name: remove html directory ## removeing html directory ## using absent ##
    ansible.builtin.file:
      path: /usr/share/nginx/html/ ## path means like this /usr/share/nginx/html/ ##
      state: absent

  - name: create html directory ## again creating html directory same module but state different ##
    ansible.builtin.file:
      path: /usr/share/nginx/html/ 
      state: directory

  - name: download web application ## application or artifact ##
    ansible.builtin.get_url:  ## downloading web application content in /tmp directory ## using get_url ##
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name: exact web application ## exacting web application in html directory form src to dest ##
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy roboshop conf ## creaded roboshop conf file copying file from roboshop.conf to /etc/nginx/default.d/roboshop.conf ##  
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: restart nginx ## restarting and enabled nginx ##
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes 
    